### ISSUE TITLE
No explicit php dependencies

### ISSUE THREAD

**Issue by danbraik** [apiato/documentation#36]
hi I had some trouble running phpunit tests.
the first time because I changed the url to localhost:8080.

but I needed to install php extension like php-bcmath
it would be nice to link to Laravel php requirements during the install process

thanks

**Comment by moslem-deris** [comment]
@danbraik Is this issue related to this repo?
I think you need to open this issue here https://github.com/apiato/apiato/issues

**Comment by moslem-deris** [comment]
@Mohammad-Alavi Check this out

**Comment by moslem-deris** [comment]
This is already done.
