### ISSUE TITLE
Using magic call method - no IDE support

### ISSUE THREAD

**Issue by Kyslik** [apiato/documentation#4]
Why do you recommend using [magic call method](http://docs.apiato.io/miscellaneous/magical-call/) everywhere instead of using Laravel's injecting feature?

>Controllers should use the function call to call Actions. (do not manually inject the Action and invoke the run).

Example gist of injecting instead https://gist.github.com/Kyslik/46eaa61c4f9a49b09935eebe7fa5b7be

```php
private $task;

__constructor(WhateverTask $task) {
    $this->task = $task
}

public function someFunction(SomeRequest $r) {
    $this->task->run($r);
    // instead of doing the following:
    // return Apiato::call('Container@WhateverTask', [$request]);
}
```

I am probably not used to this kind of calling thus it irritates me :D.

--- 

What are advantages of using magic call instead of just injecting dependencies?

**Comment by Kyslik** [comment]
Yea, I rewrote Authorization container a bit using DI and its perfect since IDE (PhpStorm) understands what is going on... On other hand now I have `->run()` everywhere.

**Comment by johannesschobel** [comment]
You can also directly put annotations in order to tell the IDE what type of object this is.. Like this:

```php
/** @var User $user */
$user = Apiato::call('User@FindUserByIdTask', [$id]);
```

This will "typehint" the IDE so that it knows, that `$user` is actually a `User` object.. Might help you in this case?

**Comment by Kyslik** [comment]
I know I do that in tests when I use factories, its not about what the task returns but to see task itself when CMD+click.

**Comment by johannesschobel** [comment]
Yes, that is why i still use the old
```php
$user = $this->call(FindUserByIdTask::class, [$id]);
```
syntax.. Because this one allows you to CMD+click to "navigate" to the other files / classes..

**Comment by Kyslik** [comment]
I know about that as well :D, its not about just about cmd+click, its simply IDE intelli sense is disabled, suggestions, return types, parameters it takes... (even tho if tasks/action has only one method its intelli sense seems to be useless).

I am not advocating here why use/not use magical call I wanted to ask if it has any downsides to **not** using it.

So far its:

>And have them all pass through the same function "Magic Call" which can detect missing containers in app, not on the interpreter level.

And I can write integration tests that will alert me instead of Apiato framework.
