### ISSUE TITLE
Update framework `docusaurus` to the latest stable version

### ISSUE THREAD

**Issue by mderis** [apiato/documentation#62]
Now we are using `docusaurus` version `2.0.0-beta.6` which is an old version of the framework and we need to update it to the latest stable version which is `2.0.1` in time of creating this issue.

**Comment by rscarrasco** [comment]
I'm working on it, but I have stumbled upon this:

```
[ERROR] Unable to build website for locale en.
[ERROR] ValidationError: "algolia.appId" is required. If you haven't migrated to the new DocSearch infra, please refer to the blog post for instructions: https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration
```

I checked the mentioned page, and it states:

> In the next few weeks, Docusaurus site owners will receive an email inviting them to join their personal Algolia application.
> 
> This email will include a new appId and apiKey to use in your Docusaurus configuration.
> 
> The only things you have to do:
>
>  * Join the Algolia application (eventually creating a new Algolia account)
>  *  Update your site configuration.

So, `docusaurus.config.js` now have to declare:

```js
const config = {
  themeConfig: {
    algolia: {
      appId: '<NEW_APP_ID>',
      apiKey: '<NEW_SEARCH_API_KEY>',
    },
  },
};

module.exports = config;
```

But since I am not the site owner (in fact, I'm just a newcomer), I do not have neither the `appId`, nor the `appKey`.

This very page also states:

> These keys are not secrets and can be added to your Git repository.

I need someone to provide me these two values. I believe that updating this config may fix #63. Anyone can help me?

**Comment by mderis** [comment]
Hi @rscarrasco ,

Kindly let me know if this is the correct creds you need:

Application ID: `OZKEC9E27Y`
Search API Key: `94a1a71e8682dac72c8708fa75280e2a`

_`This is the public API key which can be safely used in your frontend code.This key is usable for search queries and it's also able to list the indices you've got access to.`_

**Comment by rscarrasco** [comment]
@mderis It is! Thanks for sharing it! I'll keep working on this issue. Hope to have it done soon.

**Comment by mderis** [comment]
@rscarrasco thank you for your contribution.
