### ISSUE TITLE
Modify the repository link in the About section

### ISSUE THREAD

**Issue by mjpakzad** [apiato/documentation#77]
The URL of the repository in the About section is [docs.apiato.io](http://docs.apiato.io/) but the true URL that docs placed on [apiato.io/docs](https://apiato.io/docs/).
![about-section](https://user-images.githubusercontent.com/3949721/216836108-90c9f378-5525-4437-81a4-c4ed8413a9a7.jpg)

**Comment by mderis** [comment]
@mjpakzad Thank you for your report.
This has been fixed for now.
