### ISSUE TITLE
Support Issue

### ISSUE THREAD

**Issue by alovega** [apiato/documentation#89]
I currently have an issue with your documentation,
You have clearly explained the architecture design of apiato kudos for that. 
But when it comes to implementation of an application and testing the implemention there is nothing mentioned in you documentation i.e
I am trying to upgrade a legacy code that used apiato I can't find any useful resource that show implementation of routing and user defined containers

**Comment by alovega** [comment]
I have clearly created a container an provisioned a controller class called controller use the code generator to define actions and routing but I am getting the below error

![Uploading Screenshot 2023-07-22 at 20.58.14.png…]()

**Comment by Mohammad-Alavi** [comment]
It is indeed true.
I have been hard at work for the past month to rewrite the whole documentation. I need 5 6 more workdays to finish and release it.

You can pull and see it in [v12](https://github.com/apiato/documentation/tree/v12) branch.

@alovega Can you tell me again what part of the documentation you think needs improvement?

P.S. Your image isnt loading for me.

**Comment by alovega** [comment]
You can add a tutorial showing how to successfully create both inbuilt and user defined containers and register routing and everything that a container would need to function as a wrapper from crud endpoint methods

**Comment by alovega** [comment]
Another one showing how to successfully migrate from deprecated functions such as DataTransporters if you are coming from apiato version 9.0 and below
